### ISSUE TITLE
template code

### ISSUE THREAD

**Issue by josephholler** [HEGSRR/HEGSRR-Template#12]
- [x] replace `01-r_script.r` with a markdown template, or possibly include both by having a template that calls this helper R script.
- [x] include `here` and functions to set up directory paths.
- [x] include starter rmarkdown variables / setup
- [x] create a python jupyter notebook version of the same

**Comment by doabell** [comment]
Preliminary work done in commit 8209ab8 - soliciting comments.

**Comment by josephholler** [comment]
Good start!

Let's strip out the default content, as I just did in 028ffb4ab75d5addf3e27b55e32c2ec041b628a8 and add in creation of the main here() paths in both the .rmd and .ipynb ?

Is there a more foolproof option for a jupyter notebook to write environment info as the notebook is run, without requiring folks to remember to run something afterward?

**Comment by josephholler** [comment]
@doabell -- over the next week, can we:
- [ ] include all the other markdown code for an analysis plan into the python notebook template
- [ ] add use of the `citation` function in R to create a `.bib` file of citations for all the packages used? This could probably be saved in the compendium root as something like `software.bib` 
- [ ] if there is any analogous function in python to create a bib file based on packages, let's implement that!

**Comment by josephholler** [comment]
@doabell : I'm curious what you think about having a separate environment set-up script / instruction file for python, which would install pipenv, pigar, and pyhere and contain the instructions for cleaning the environment.txt file? 

Then the `computational environment` section of the python notebook would contain the normally-skipped code to 1) install packages using environment.txt and 2) generate the environment.txt, as well as code that will always be run to load packages and set pyhere paths analogous to the R here paths in the `rmd` template. 

Separating these initial installs would declutter the notebook from the one-time tasks of setting up the basic python environment. However, would dividing it up like this make it any more difficult to use services like Binder? 

If we split into two, it'd be:

00-Python-environment-setup.py   (easier as script or as notebook?)
01-Jupyter_notebook.ipynb

**Comment by doabell** [comment]
@josephholler Sure, that does indeed makes more sense
`00-Python-environment-setup.ipynb` would still be a notebook, perhaps with "record" and "install" chunks.

**Comment by josephholler** [comment]
Ok, you can try doing it. I think the record step still needs to be in the main 01-Jupyter_notebook.ipynb notebook, because that is where the packages will be loaded. Also, the package loading makes sense in the main notebook as part of the documentation of the computational environment.

**Comment by josephholler** [comment]
Seems like notebook metadata may not be straightforward... we can pause that thought and the related heading levels.

**Comment by josephholler** [comment]
Done, until there's a neat package for generating a .bib file for python packages used in a compendium.
