### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by josephholler** [HEGSRR/HEGSRR-Template#14]
This issue is a reminder to release a version 2.0 of this template prior to fall courses & workshops.

**Comment by josephholler** [comment]
our prerelease was version 0.1, so this will actually be v.1.0

**Comment by josephholler** [comment]
@Peter-Kedron : this is the last call for a final proofread of the template before releasing version 1.0

**Comment by Peter-Kedron** [comment]
I think this looks good. My one suggestion is that we move the citation reference to the top of the top-level readme. If we want people to cite, I think we have a much better chance if that is right in their face when they land on the page.

**Comment by Peter-Kedron** [comment]
Yes, exactly. Close the issue if you are satisfied.
