### ISSUE TITLE
containers

### ISSUE THREAD

**Issue by josephholler** [HEGSRR/HEGSRR-Template#6]
Github just enhanced a feature for sharing Docker containers in an organization!
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by doabell** [comment]
[rbundler](https://cran.r-project.org/package=rbundler) has been removed from CRAN. Similar functionality can be found in the packages [rang](https://cran.r-project.org/web/packages/rang/index.html), [renv](https://cran.r-project.org/web/packages/renv/index.html), or [groundhog](https://cran.r-project.org/web/packages/groundhog/index.html).

Docker containers are often published and distributed through [Docker Hub](https://www.docker.com/products/docker-hub/).

**Comment by josephholler** [comment]
For now, we are going to support decentralized approaches to reproducing the computational environment which do not hinge on server services like Docker.
